export const DOCUMENT_CATEGORY = {
  PRODUCT_REQUIREMENT: "PRODUCT_REQUIREMENT",
  ARCHITECTURE_DIAGRAM: "ARCHITECTURE_DIAGRAM",
  UI_DESIGN: "UI_DESIGN",
  CLIENT_DOCUMENT: "CLIENT_DOCUMENT",
  PROJECT_PLAN: "PROJECT_PLAN",
  API_SPECIFICATION: "API_SPECIFICATION",
  IMPLEMENTATION_SCREENSHOT: "IMPLEMENTATION_SCREENSHOT",
  OUTPUT_FILE: "OUTPUT_FILE",
  TECHNICAL_NOTE: "TECHNICAL_NOTE",
  TEST_DATA: "TEST_DATA",
  BUG_SCREENSHOT: "BUG_SCREENSHOT",
  SCREEN_RECORDING: "SCREEN_RECORDING",
  CONSOLE_LOG: "CONSOLE_LOG",
  NETWORK_LOG: "NETWORK_LOG",
  REPRODUCTION_FILE: "REPRODUCTION_FILE",
  INVOICE: "INVOICE",
  PAYMENT_PROOF: "PAYMENT_PROOF",
  ORDER_ATTACHMENT: "ORDER_ATTACHMENT",
  CONTRACT: "CONTRACT",
  RECEIPT: "RECEIPT",
  OTHER: "OTHER",
} as const;

export type DocumentCategory =
  (typeof DOCUMENT_CATEGORY)[keyof typeof DOCUMENT_CATEGORY];

export const DOCUMENT_CATEGORIES = Object.values(DOCUMENT_CATEGORY) as [
  DocumentCategory,
  ...DocumentCategory[],
];
